# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listview.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(3, 130, 168);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 20, 47, 21))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("incomeLabel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(450, 20, 51, 21))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("expensesLabel")
        self.listOfIncome = QtWidgets.QListWidget(self.centralwidget)
        self.listOfIncome.setGeometry(QtCore.QRect(80, 50, 121, 391))
        self.listOfIncome.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listOfIncome.setObjectName("listOfIncome")
        self.listOfExpenses = QtWidgets.QListWidget(self.centralwidget)
        self.listOfExpenses.setGeometry(QtCore.QRect(450, 50, 131, 391))
        self.listOfExpenses.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listOfExpenses.setObjectName("listOfExpenses")
        self.moneyleftLabel = QtWidgets.QLabel(self.centralwidget)
        self.moneyleftLabel.setGeometry(QtCore.QRect(80, 480, 131, 31))
        self.moneyleftLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.moneyleftLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.moneyleftLabel.setObjectName("moneyleftLabel")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(670, 480, 75, 23))
        self.saveButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.saveButton.setObjectName("saveButton")
        self.listOfIncomeSEK = QtWidgets.QListWidget(self.centralwidget)
        self.listOfIncomeSEK.setGeometry(QtCore.QRect(200, 50, 141, 391))
        self.listOfIncomeSEK.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listOfIncomeSEK.setObjectName("listOfIncomeSEK")
        self.listOfExpensesSEK = QtWidgets.QListWidget(self.centralwidget)
        self.listOfExpensesSEK.setGeometry(QtCore.QRect(580, 50, 131, 391))
        self.listOfExpensesSEK.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listOfExpensesSEK.setObjectName("listOfExpensesSEK")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Income"))
        self.label_2.setText(_translate("MainWindow", "Expenses"))
        self.moneyleftLabel.setText(_translate("MainWindow", "Money left to spend:"))
        self.saveButton.setText(_translate("MainWindow", "Save"))

class BudgetScreen(QMainWindow, Ui_MainWindow):

    def __init__(self):
        super().__init__()  # Call the superclass constructor
        self.setupUi(self)  # Run the code that creates the UI layout
        self.listOfIncomeSources = ["Salary"]
        self.listOfIncome.addItems(self.listOfIncomeSources)
        self.listOfIncomeSourcesSEK = ["20000 SEK"]
        self.listOfIncomeSEK.addItems(self.listOfIncomeSourcesSEK)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = BudgetScreen()
    MainWindow.show()
    sys.exit(app.exec_())
