from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from account import Account
import database_connection as DB

class Ui_LoginScreen(object):
    """Main Login Window."""

    def setupUi(self, MainWindow):
        self.customer = Account.getInstance()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1917, 1010)
        MainWindow.setStyleSheet("background-color: rgb(3, 130, 168);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(850, 360, 111, 31))
        self.label.setMinimumSize(QtCore.QSize(71, 0))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(850, 490, 111, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(850, 400, 171, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(850, 530, 171, 31))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(860, 690, 151, 41))
        self.pushButton.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 880, 291, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.STMPlogo = QtWidgets.QLabel(self.centralwidget)
        self.STMPlogo.setGeometry(QtCore.QRect(0, 0, 450, 200))
        self.STMPlogo.setText("")
        self.STMPlogo.setPixmap(QtGui.QPixmap("STMP-Logo.png"))
        self.STMPlogo.setScaledContents(True)
        self.STMPlogo.setObjectName("STMPlogo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1917, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "STMP"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Username</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Password</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Log in"))
        self.pushButton_2.setText(_translate("MainWindow", "Not Registered? Click here")
        )


class Ui_FirstLoginScreen(object):
    def setupUi(self, MainWindow):
        self.customer = Account.getInstance()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 572)
        MainWindow.setStyleSheet("background-color: rgb(3, 130, 168);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 20, 47, 21))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(450, 20, 51, 21))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.popUp = QMessageBox()
        self.popUp.setWindowTitle("Error")
        self.popUp.setText("Bad input, please only enter integers")
        self.listOfIncome = QtWidgets.QListWidget(self.centralwidget)
        self.listOfIncome.setGeometry(QtCore.QRect(80, 50, 121, 391))
        self.listOfIncome.setStyleSheet("background-color:\
                                        rgb(255, 255, 255);")
        self.listOfIncome.setObjectName("listOfIncome")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listOfIncome.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfIncome.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfIncome.addItem(item)
        self.listOfExpenses = QtWidgets.QListWidget(self.centralwidget)
        self.listOfExpenses.setGeometry(QtCore.QRect(450, 50, 131, 391))
        self.listOfExpenses.setStyleSheet("background-color: \
                                          rgb(255, 255, 255);")
        self.listOfExpenses.setObjectName("listOfExpenses")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(700, 480, 75, 23))
        self.saveButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.saveButton.setObjectName("saveButton")
        self.listOfIncomeSEK = QtWidgets.QListWidget(self.centralwidget)
        self.listOfIncomeSEK.setGeometry(QtCore.QRect(200, 50, 141, 391))
        self.listOfIncomeSEK.setStyleSheet("background-color: \
                                            rgb(255, 255, 255);")
        self.listOfIncomeSEK.setObjectName("listOfIncomeSEK")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listOfIncomeSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(
                      QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable |
                      QtCore.Qt.ItemIsDragEnabled |
                      QtCore.Qt.ItemIsUserCheckable |
                      QtCore.Qt.ItemIsEnabled
                      )
        self.listOfIncomeSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfIncomeSEK.addItem(item)
        self.listOfExpensesSEK = QtWidgets.QListWidget(self.centralwidget)
        self.listOfExpensesSEK.setGeometry(QtCore.QRect(580, 50, 131, 391))
        self.listOfExpensesSEK.setStyleSheet("background-color: \
                                             rgb(255, 255, 255);")
        self.listOfExpensesSEK.setObjectName("listOfExpensesSEK")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable |
                      QtCore.Qt.ItemIsEditable |
                      QtCore.Qt.ItemIsDragEnabled |
                      QtCore.Qt.ItemIsUserCheckable |
                      QtCore.Qt.ItemIsEnabled)
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable |
                      QtCore.Qt.ItemIsEditable |
                      QtCore.Qt.ItemIsDragEnabled |
                      QtCore.Qt.ItemIsUserCheckable |
                      QtCore.Qt.ItemIsEnabled)
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable |
                      QtCore.Qt.ItemIsEditable |
                      QtCore.Qt.ItemIsDragEnabled |
                      QtCore.Qt.ItemIsUserCheckable |
                      QtCore.Qt.ItemIsEnabled)
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable |
                      QtCore.Qt.ItemIsEditable |
                      QtCore.Qt.ItemIsDragEnabled |
                      QtCore.Qt.ItemIsUserCheckable |
                      QtCore.Qt.ItemIsEnabled)
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable |
                      QtCore.Qt.ItemIsEditable |
                      QtCore.Qt.ItemIsDragEnabled |
                      QtCore.Qt.ItemIsUserCheckable |
                      QtCore.Qt.ItemIsEnabled)
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable |
                      QtCore.Qt.ItemIsEditable |
                      QtCore.Qt.ItemIsDragEnabled |
                      QtCore.Qt.ItemIsUserCheckable |
                      QtCore.Qt.ItemIsEnabled)
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable |
                      QtCore.Qt.ItemIsEditable |
                      QtCore.Qt.ItemIsDragEnabled |
                      QtCore.Qt.ItemIsUserCheckable |
                      QtCore.Qt.ItemIsEnabled)
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable |
                      QtCore.Qt.ItemIsEditable |
                      QtCore.Qt.ItemIsDragEnabled |
                      QtCore.Qt.ItemIsUserCheckable |
                      QtCore.Qt.ItemIsEnabled)
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable |
                      QtCore.Qt.ItemIsEditable |
                      QtCore.Qt.ItemIsDragEnabled |
                      QtCore.Qt.ItemIsUserCheckable |
                      QtCore.Qt.ItemIsEnabled)
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable |
                      QtCore.Qt.ItemIsEditable |
                      QtCore.Qt.ItemIsDragEnabled |
                      QtCore.Qt.ItemIsUserCheckable |
                      QtCore.Qt.ItemIsEnabled)
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable |
                      QtCore.Qt.ItemIsEditable |
                      QtCore.Qt.ItemIsDragEnabled |
                      QtCore.Qt.ItemIsUserCheckable |
                      QtCore.Qt.ItemIsEnabled)
        self.listOfExpensesSEK.addItem(item)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 480, 75, 23))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 0, 211, 21))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Income"))
        self.label_2.setText(_translate("MainWindow", "Expenses"))
        __sortingEnabled = self.listOfIncome.isSortingEnabled()
        self.listOfIncome.setSortingEnabled(False)
        item = self.listOfIncome.item(0)
        item.setText(_translate("MainWindow", "Type:"))
        item = self.listOfIncome.item(1)
        item.setText(_translate("MainWindow", "Total Income"))
        self.listOfIncome.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listOfExpenses.isSortingEnabled()
        self.listOfExpenses.setSortingEnabled(False)
        item = self.listOfExpenses.item(0)
        item.setText(_translate("MainWindow", "Type:"))
        item = self.listOfExpenses.item(1)
        item.setText(_translate("MainWindow", "Fixed expenses:"))
        item = self.listOfExpenses.item(2)
        item.setText(_translate("MainWindow", "Subscriptions"))
        item = self.listOfExpenses.item(3)
        item.setText(_translate("MainWindow", "Insurance"))
        item = self.listOfExpenses.item(4)
        item.setText(_translate("MainWindow", "Rent"))
        item = self.listOfExpenses.item(5)
        item.setText(_translate("MainWindow", "Others"))
        item = self.listOfExpenses.item(10)
        item.setText(_translate("MainWindow", "Variable expenses:"))
        item = self.listOfExpenses.item(11)
        item.setText(_translate("MainWindow", "Transportation"))
        item = self.listOfExpenses.item(12)
        item.setText(_translate("MainWindow", "Entertainment"))
        item = self.listOfExpenses.item(13)
        item.setText(_translate("MainWindow", "Clothes"))
        item = self.listOfExpenses.item(14)
        item.setText(_translate("MainWindow", "Hygien"))
        item = self.listOfExpenses.item(15)
        item.setText(_translate("MainWindow", "Food"))
        item = self.listOfExpenses.item(16)
        item.setText(_translate("MainWindow", "Bills"))
        item = self.listOfExpenses.item(17)
        item.setText(_translate("MainWindow", "Others"))
        self.listOfExpenses.setSortingEnabled(__sortingEnabled)
        self.saveButton.setText(_translate("MainWindow", "Save"))
        __sortingEnabled = self.listOfIncomeSEK.isSortingEnabled()
        self.listOfIncomeSEK.setSortingEnabled(False)
        item = self.listOfIncomeSEK.item(0)
        item.setText(_translate("MainWindow", "Amount:"))
        item = self.listOfIncomeSEK.item(1)
        item.setText(_translate("MainWindow", "0"))
        self.listOfIncomeSEK.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listOfExpensesSEK.isSortingEnabled()
        self.listOfExpensesSEK.setSortingEnabled(False)
        item = self.listOfExpensesSEK.item(0)
        item.setText(_translate("MainWindow", "Amount:"))
        item = self.listOfExpensesSEK.item(2)
        item.setText(_translate("MainWindow", "0"))
        item = self.listOfExpensesSEK.item(3)
        item.setText(_translate("MainWindow", "0"))
        item = self.listOfExpensesSEK.item(4)
        item.setText(_translate("MainWindow", "0"))
        item = self.listOfExpensesSEK.item(5)
        item.setText(_translate("MainWindow", "0"))
        item = self.listOfExpensesSEK.item(11)
        item.setText(_translate("MainWindow", "0"))
        item = self.listOfExpensesSEK.item(12)
        item.setText(_translate("MainWindow", "0"))
        item = self.listOfExpensesSEK.item(13)
        item.setText(_translate("MainWindow", "0"))
        item = self.listOfExpensesSEK.item(14)
        item.setText(_translate("MainWindow", "0"))
        item = self.listOfExpensesSEK.item(15)
        item.setText(_translate("MainWindow", "0"))
        item = self.listOfExpensesSEK.item(16)
        item.setText(_translate("MainWindow", "0"))
        item = self.listOfExpensesSEK.item(17)
        item.setText(_translate("MainWindow", "0"))
        self.listOfExpensesSEK.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "Back"))
        self.label_3.setText(_translate("MainWindow",
                                        "Set your income and expenses"))


class Ui_MenuScreen(object):
    """Menu Window"""

    def setupUi(self, MainWindow):
        self.customer = Account.getInstance()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(601, 410)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 50, 100, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 221, 81))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("STMP-Logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(260, 100, 131, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 140, 131, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 180, 131, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(260, 220, 131, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 300, 131, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 601, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", f"Welcome,\
                                      {self.customer.first_name}"))
        self.pushButton.setText(_translate("MainWindow", "Make a budget"))
        self.pushButton_2.setText(_translate("MainWindow",
                                             "Create long-term savings"))
        self.pushButton_3.setText(_translate("MainWindow", "Set your buffert"))
        self.pushButton_4.setText(_translate("MainWindow", "Economic Overview"))
        self.pushButton_5.setText(_translate("MainWindow", "Log out"))


class Ui_RegisterScreen(object):
    """Register window."""

    def setupUi(self, MainWindow):
        self.customer = Account.getInstance()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1917, 1010)
        MainWindow.setStyleSheet("background-color: rgb(3, 130, 168);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(920, 340, 91, 51))
        self.label.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"")
        self.label.setObjectName("label")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(910, 430, 111, 21))
        self.username.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.username.setObjectName("lineEdit")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(910, 490, 111, 21))
        self.password.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(910, 410, 111, 16))
        self.label_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(910, 470, 91, 16))
        self.label_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(920, 690, 81, 41))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.lastname = QtWidgets.QLineEdit(self.centralwidget)
        self.lastname.setGeometry(QtCore.QRect(910, 610, 111, 21))
        self.lastname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lastname.setObjectName("lineEdit_3")
        self.firstname = QtWidgets.QLineEdit(self.centralwidget)
        self.firstname.setGeometry(QtCore.QRect(910, 550, 111, 21))
        self.firstname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.firstname.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(910, 530, 111, 16))
        self.label_5.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(910, 590, 91, 16))
        self.label_6.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.STMPlogo = QtWidgets.QLabel(self.centralwidget)
        self.STMPlogo.setGeometry(QtCore.QRect(0, 0, 450, 200))
        self.STMPlogo.setText("")
        self.STMPlogo.setPixmap(QtGui.QPixmap("STMP-Logo.png"))
        self.STMPlogo.setScaledContents(True)
        self.STMPlogo.setObjectName("STMPlogo")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 920, 121, 61))
        self.pushButton_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1917, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.popUp = QMessageBox()
        self.popUp.setWindowTitle("Error")
        self.popUp.setText("Incorrect email, please try again")
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
     
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Register"))
        self.label_2.setText(_translate("MainWindow", "Email"))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.pushButton.setText(_translate("MainWindow", "Register"))
        self.label_5.setText(_translate("MainWindow", "First name"))
        self.label_6.setText(_translate("MainWindow", "Last name"))
        self.pushButton_2.setText(_translate("MainWindow", "Back"))


class Ui_BudgetChoiceScreen(object):
    def setupUi(self, MainWindow):
        self.customer = Account.getInstance()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(604, 392)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 170, 131, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 120, 131, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 280, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 0, 241, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("STMP-Logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 604, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow",
                                  "Get help with budget"))
        self.pushButton_3.setText(_translate("MainWindow",
                                             "Make your own budget"))
        self.pushButton.setText(_translate("MainWindow", "Back"))


class Ui_BudgetScreen(object):
    def setupUi(self, MainWindow):
        self.customer = Account.getInstance()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 572)
        MainWindow.setStyleSheet("background-color: rgb(3, 130, 168);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 20, 47, 21))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(450, 20, 51, 21))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(500, 0, 301, 101))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("STMP-Logo.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.listOfIncome = QtWidgets.QListWidget(self.centralwidget)
        self.listOfIncome.setGeometry(QtCore.QRect(80, 50, 121, 391))
        self.listOfIncome.setStyleSheet("background-color: \
                                        rgb(255, 255, 255);")
        self.listOfIncome.setObjectName("listOfIncome")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listOfIncome.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfIncome.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfIncome.addItem(item)
        self.listOfExpenses = QtWidgets.QListWidget(self.centralwidget)
        self.listOfExpenses.setGeometry(QtCore.QRect(450, 50, 131, 391))
        self.listOfExpenses.setStyleSheet("background-color: \
                                          rgb(255, 255, 255);")
        self.listOfExpenses.setObjectName("listOfExpenses")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listOfExpenses.addItem(item)
        self.moneyleftLabel = QtWidgets.QLabel(self.centralwidget)
        self.moneyleftLabel.setGeometry(QtCore.QRect(260, 450, 131, 41))
        self.moneyleftLabel.setStyleSheet("background-color: \
                                          rgb(255, 255, 255);")
        self.moneyleftLabel.setAlignment(QtCore.Qt.AlignHCenter |
                                         QtCore.Qt.AlignTop)
        self.moneyleftLabel.setObjectName("moneyleftLabel")
        self.saving_goal = QtWidgets.QLabel(self.centralwidget)
        self.saving_goal.setGeometry(QtCore.QRect(410, 450, 131, 41))
        self.saving_goal.setStyleSheet("background-color: \
                                          rgb(255, 255, 255);")
        self.saving_goal.setAlignment(QtCore.Qt.AlignHCenter |
                                         QtCore.Qt.AlignTop)
        self.saving_goal.setObjectName("saving_goal")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(700, 480, 75, 23))
        self.saveButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.saveButton.setObjectName("saveButton")
        self.listOfIncomeSEK = QtWidgets.QListWidget(self.centralwidget)
        self.listOfIncomeSEK.setGeometry(QtCore.QRect(200, 50, 141, 391))
        self.listOfIncomeSEK.setStyleSheet("background-color: \
                                            rgb(255, 255, 255);")
        self.listOfIncomeSEK.setObjectName("listOfIncomeSEK")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listOfIncomeSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable |
                      QtCore.Qt.ItemIsEditable |
                      QtCore.Qt.ItemIsDragEnabled |
                      QtCore.Qt.ItemIsUserCheckable |
                      QtCore.Qt.ItemIsEnabled)
        self.listOfIncomeSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfIncomeSEK.addItem(item)
        self.listOfExpensesSEK = QtWidgets.QListWidget(self.centralwidget)
        self.listOfExpensesSEK.setGeometry(QtCore.QRect(580, 50, 131, 391))
        self.listOfExpensesSEK.setStyleSheet("background-color: \
                                             rgb(255, 255, 255);")
        self.listOfExpensesSEK.setObjectName("listOfExpensesSEK")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable |
                      QtCore.Qt.ItemIsEditable |
                      QtCore.Qt.ItemIsDragEnabled |
                      QtCore.Qt.ItemIsUserCheckable |
                      QtCore.Qt.ItemIsEnabled)
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable |
                      QtCore.Qt.ItemIsEditable |
                      QtCore.Qt.ItemIsDragEnabled |
                      QtCore.Qt.ItemIsUserCheckable |
                      QtCore.Qt.ItemIsEnabled)
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable |
                      QtCore.Qt.ItemIsEditable |
                      QtCore.Qt.ItemIsDragEnabled |
                      QtCore.Qt.ItemIsUserCheckable |
                      QtCore.Qt.ItemIsEnabled)
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable |
                      QtCore.Qt.ItemIsEditable |
                      QtCore.Qt.ItemIsDragEnabled |
                      QtCore.Qt.ItemIsUserCheckable |
                      QtCore.Qt.ItemIsEnabled)
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable |
                      QtCore.Qt.ItemIsEditable |
                      QtCore.Qt.ItemIsDragEnabled |
                      QtCore.Qt.ItemIsUserCheckable |
                      QtCore.Qt.ItemIsEnabled)
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable |
                      QtCore.Qt.ItemIsEditable |
                      QtCore.Qt.ItemIsDragEnabled |
                      QtCore.Qt.ItemIsUserCheckable |
                      QtCore.Qt.ItemIsEnabled)
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable |
                      QtCore.Qt.ItemIsEditable |
                      QtCore.Qt.ItemIsDragEnabled |
                      QtCore.Qt.ItemIsUserCheckable |
                      QtCore.Qt.ItemIsEnabled)
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable |
                      QtCore.Qt.ItemIsEditable |
                      QtCore.Qt.ItemIsDragEnabled |
                      QtCore.Qt.ItemIsUserCheckable |
                      QtCore.Qt.ItemIsEnabled)
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable |
                      QtCore.Qt.ItemIsEditable |
                      QtCore.Qt.ItemIsDragEnabled |
                      QtCore.Qt.ItemIsUserCheckable |
                      QtCore.Qt.ItemIsEnabled)
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable |
                      QtCore.Qt.ItemIsEditable |
                      QtCore.Qt.ItemIsDragEnabled |
                      QtCore.Qt.ItemIsUserCheckable |
                      QtCore.Qt.ItemIsEnabled)
        self.listOfExpensesSEK.addItem(item)
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(20, 480, 75, 23))
        self.backButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.backButton.setObjectName("backButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 470, 47, 13))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(450, 470, 47, 13))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.popUp = QMessageBox()
        self.popUp.setWindowTitle("Error")
        self.popUp.setText("Bad input, please enter only positive integers")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Income"))
        self.label_2.setText(_translate("MainWindow", "Expenses"))
        self.saving_goal.setText(_translate("MainWindow", "Your saving goal:"))
        __sortingEnabled = self.listOfIncome.isSortingEnabled()
        self.listOfIncome.setSortingEnabled(False)
        item = self.listOfIncome.item(0)
        item.setText(_translate("MainWindow", "Type:"))
        item = self.listOfIncome.item(1)
        item.setText(_translate("MainWindow", "Total Income"))
        self.listOfIncome.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listOfExpenses.isSortingEnabled()
        self.listOfExpenses.setSortingEnabled(False)
        item = self.listOfExpenses.item(0)
        item.setText(_translate("MainWindow", "Type:"))
        item = self.listOfExpenses.item(1)
        item.setText(_translate("MainWindow", "Fixed expenses:"))
        item = self.listOfExpenses.item(2)
        item.setText(_translate("MainWindow", "Subscriptions"))
        item = self.listOfExpenses.item(3)
        item.setText(_translate("MainWindow", "Insurance"))
        item = self.listOfExpenses.item(4)
        item.setText(_translate("MainWindow", "Rent"))
        item = self.listOfExpenses.item(5)
        item.setText(_translate("MainWindow", "Others"))
        item = self.listOfExpenses.item(10)
        item.setText(_translate("MainWindow", "Variable expenses:"))
        item = self.listOfExpenses.item(11)
        item.setText(_translate("MainWindow", "Food"))
        item = self.listOfExpenses.item(12)
        item.setText(_translate("MainWindow", "Bills"))
        item = self.listOfExpenses.item(13)
        item.setText(_translate("MainWindow", "Transportation"))
        item = self.listOfExpenses.item(14)
        item.setText(_translate("MainWindow", "Hygien"))
        item = self.listOfExpenses.item(15)
        item.setText(_translate("MainWindow", "Clothes"))
        item = self.listOfExpenses.item(16)
        item.setText(_translate("MainWindow", "Entertainment"))
        item = self.listOfExpenses.item(17)
        item.setText(_translate("MainWindow", "Others"))
        item = self.listOfExpenses.item(20)
        item.setText(_translate("MainWindow", "Buffert"))
        self.listOfExpenses.setSortingEnabled(__sortingEnabled)
        self.moneyleftLabel.setText(_translate("MainWindow",
                                               "Money left to spend:"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        __sortingEnabled = self.listOfIncomeSEK.isSortingEnabled()
        self.listOfIncomeSEK.setSortingEnabled(False)
        item = self.listOfIncomeSEK.item(0)
        item.setText(_translate("MainWindow", "Amount:"))
        item = self.listOfIncomeSEK.item(1)
        item.setText(_translate("MainWindow", "0"))
        self.listOfIncomeSEK.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listOfExpensesSEK.isSortingEnabled()
        self.listOfExpensesSEK.setSortingEnabled(False)
        item = self.listOfExpensesSEK.item(0)
        item.setText(_translate("MainWindow", "Amount:"))
        item = self.listOfExpensesSEK.item(1)
        item.setText(_translate("MainWindow", "0"))
        item = self.listOfExpensesSEK.item(2)
        item.setText(_translate("MainWindow", "0"))
        item = self.listOfExpensesSEK.item(3)
        item.setText(_translate("MainWindow", "0"))
        item = self.listOfExpensesSEK.item(4)
        item.setText(_translate("MainWindow", "0"))
        item = self.listOfExpensesSEK.item(5)
        item.setText(_translate("MainWindow", "0"))
        item = self.listOfExpensesSEK.item(10)
        item.setText(_translate("MainWindow", "0"))
        item = self.listOfExpensesSEK.item(11)
        item.setText(_translate("MainWindow", "0"))
        item = self.listOfExpensesSEK.item(12)
        item.setText(_translate("MainWindow", "0"))
        item = self.listOfExpensesSEK.item(13)
        item.setText(_translate("MainWindow", "0"))
        item = self.listOfExpensesSEK.item(14)
        item.setText(_translate("MainWindow", "0"))
        item = self.listOfExpensesSEK.item(15)
        item.setText(_translate("MainWindow", "0"))
        item = self.listOfExpensesSEK.item(16)
        item.setText(_translate("MainWindow", "0"))
        item = self.listOfExpensesSEK.item(17)
        item.setText(_translate("MainWindow", "0"))
        item = self.listOfExpensesSEK.item(20)
        item.setText(_translate("MainWindow", "0"))
        
        

        self.listOfExpensesSEK.setSortingEnabled(__sortingEnabled)
        self.backButton.setText(_translate("MainWindow", "Back"))
        self.label_3.setText(_translate("MainWindow", "put money left here"))


class Ui_SavinggoalScreen(object):
    def setupUi(self, MainWindow):
        self.customer = Account.getInstance()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(606, 318)
        MainWindow.setStyleSheet("background-color: rgb(3, 130, 168);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 71, 21))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.popUp = QMessageBox()
        self.popUp.setWindowTitle("Error")
        self.popUp.setText("Bad input, enter only positive numbers")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 70, 141, 20))
        self.lineEdit.setToolTip("")
        self.lineEdit.setAccessibleDescription("")
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setInputMask("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 110, 141, 20))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        # self.label_2 = QtWidgets.QLabel(self.centralwidget)
        # self.label_2.setGeometry(QtCore.QRect(50, 150, 191, 21))
        # self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        # self.label_2.setText("")
        # self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        # self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(440, 30, 151, 71))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading |
                                  QtCore.Qt.AlignLeft |
                                  QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 200, 281, 81))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("STMP-Logo.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(490, 200, 101, 23))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 150, 75, 23))
        self.pushButton_2.setStyleSheet("background-color: \
                                        rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 140, 141, 40))
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 606, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Saving goal"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow",
                                                    "Amount to save a month"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow",
                                                      "Your saving goal"))
        self.label_3.setText(_translate("MainWindow",
                                        "<html><head/><body><p>Play around and \
                                            see how long </p><p>it would take \
                                            to reach your</p><p>saving goal \
                                            or buffert</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Back"))
        self.pushButton_2.setText(_translate("MainWindow", "Calculate"))

class Ui_BuffertScreen(object):
    def setupUi(self, MainWindow):
        self.customer = Account.getInstance()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(460, 337)
        MainWindow.setStyleSheet("background-color: rgb(3, 130, 168);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 0, 251, 21))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.popUp = QMessageBox()
        self.popUp.setWindowTitle("Error")
        self.popUp.setText("Bad input, please only enter positive integers")
        self.totalincome = QtWidgets.QTextBrowser(self.centralwidget)
        self.totalincome.setGeometry(QtCore.QRect(100, 80, 256, 51))
        self.totalincome.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.totalincome.setObjectName("totalincome")
        self.totalexpenses = QtWidgets.QTextBrowser(self.centralwidget)
        self.totalexpenses.setGeometry(QtCore.QRect(100, 160, 256, 51))
        self.totalexpenses.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.totalexpenses.setObjectName("totalexpenses")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 60, 47, 13))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 140, 51, 16))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 220, 47, 13))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(260, 220, 71, 13))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.amount_of_budget = QtWidgets.QProgressBar(self.centralwidget)
        self.amount_of_budget.setGeometry(QtCore.QRect(260, 240, 91, 23))
        self.amount_of_budget.setProperty("value", 0)
        self.amount_of_budget.setObjectName("amount_of_budget")
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(380, 270, 75, 23))
        self.save_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.save_button.setObjectName("save_button")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(10, 270, 75, 21))
        self.back_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.back_button.setObjectName("back_button")
        self.buffert_input = QtWidgets.QLineEdit(self.centralwidget)
        self.buffert_input.setGeometry(QtCore.QRect(100, 240, 131, 21))
        self.buffert_input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.buffert_input.setObjectName("buffert_input")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 460, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Set your buffert"))
        self.label_2.setText(_translate("MainWindow", "Income"))
        self.label_3.setText(_translate("MainWindow", "Expenses"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.back_button.setText(_translate("MainWindow", "Back"))
        self.label_4.setText(_translate("MainWindow", "Buffert:"))
        self.label_5.setText(_translate("MainWindow", "'%' of budget"))

class Ui_EcoOverviewScreen(object):
    def setupUi(self, MainWindow):
        self.customer = Account.getInstance()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 572)
        MainWindow.setStyleSheet("background-color: rgb(3, 130, 168);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 50, 47, 21))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(490, 50, 51, 21))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.listOfIncome = QtWidgets.QListWidget(self.centralwidget)
        self.listOfIncome.setGeometry(QtCore.QRect(70, 80, 121, 151))
        self.listOfIncome.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listOfIncome.setObjectName("listOfIncome")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listOfIncome.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfIncome.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfIncome.addItem(item)
        self.listOfExpenses = QtWidgets.QListWidget(self.centralwidget)
        self.listOfExpenses.setGeometry(QtCore.QRect(490, 80, 131, 361))
        self.listOfExpenses.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listOfExpenses.setObjectName("listOfExpenses")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpenses.addItem(item)
        self.moneyleftLabel = QtWidgets.QLabel(self.centralwidget)
        self.moneyleftLabel.setGeometry(QtCore.QRect(330, 470, 141, 41))
        self.moneyleftLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.moneyleftLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.moneyleftLabel.setObjectName("moneyleftLabel")
        self.listOfIncomeSEK = QtWidgets.QListWidget(self.centralwidget)
        self.listOfIncomeSEK.setGeometry(QtCore.QRect(190, 80, 141, 151))
        self.listOfIncomeSEK.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listOfIncomeSEK.setObjectName("listOfIncomeSEK")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listOfIncomeSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfIncomeSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfIncomeSEK.addItem(item)
        self.listOfExpensesSEK = QtWidgets.QListWidget(self.centralwidget)
        self.listOfExpensesSEK.setGeometry(QtCore.QRect(620, 80, 131, 361))
        self.listOfExpensesSEK.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listOfExpensesSEK.setObjectName("listOfExpensesSEK")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listOfExpensesSEK.addItem(item)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 480, 75, 23))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, 490, 47, 13))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 260, 47, 21))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.savingsList= QtWidgets.QListWidget(self.centralwidget)
        self.savingsList.setGeometry(QtCore.QRect(70, 290, 121, 151))
        self.savingsList.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.savingsList.setObjectName("savingsList")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.savingsList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.savingsList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.savingsList.addItem(item)
        self.savingsListSEK = QtWidgets.QListWidget(self.centralwidget)
        self.savingsListSEK.setGeometry(QtCore.QRect(190, 290, 141, 151))
        self.savingsListSEK.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.savingsListSEK.setObjectName("savingsListSEK")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.savingsListSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.savingsListSEK.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.savingsListSEK.addItem(item)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(290, 0, 241, 21))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Income"))
        self.label_2.setText(_translate("MainWindow", "Expenses"))
        __sortingEnabled = self.listOfIncome.isSortingEnabled()
        self.listOfIncome.setSortingEnabled(False)
        item = self.listOfIncome.item(0)
        item.setText(_translate("MainWindow", "Type:"))
        item = self.listOfIncome.item(1)
        item.setText(_translate("MainWindow", "Total Income"))
        self.listOfIncome.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listOfExpenses.isSortingEnabled()
        self.listOfExpenses.setSortingEnabled(False)
        item = self.listOfExpenses.item(0)
        item.setText(_translate("MainWindow", "Type:"))
        item = self.listOfExpenses.item(1)
        item.setText(_translate("MainWindow", "Fixed expenses:"))
        item = self.listOfExpenses.item(2)
        item.setText(_translate("MainWindow", "Subscriptions"))
        item = self.listOfExpenses.item(3)
        item.setText(_translate("MainWindow", "Insurance"))
        item = self.listOfExpenses.item(4)
        item.setText(_translate("MainWindow", "Rent"))
        item = self.listOfExpenses.item(5)
        item.setText(_translate("MainWindow", "Others"))
        item = self.listOfExpenses.item(10)
        item.setText(_translate("MainWindow", "Variable expenses:"))
        item = self.listOfExpenses.item(11)
        item.setText(_translate("MainWindow", "Transportation"))
        item = self.listOfExpenses.item(12)
        item.setText(_translate("MainWindow", "Entertainment"))
        item = self.listOfExpenses.item(13)
        item.setText(_translate("MainWindow", "Clothes"))
        item = self.listOfExpenses.item(14)
        item.setText(_translate("MainWindow", "Hygien"))
        item = self.listOfExpenses.item(15)
        item.setText(_translate("MainWindow", "Food"))
        item = self.listOfExpenses.item(16)
        item.setText(_translate("MainWindow", "Bills"))
        item = self.listOfExpenses.item(17)
        item.setText(_translate("MainWindow", "Others"))
        self.listOfExpenses.setSortingEnabled(__sortingEnabled)
        self.moneyleftLabel.setText(_translate("MainWindow", "Money left to spend/save:"))
        __sortingEnabled = self.listOfIncomeSEK.isSortingEnabled()
        self.listOfIncomeSEK.setSortingEnabled(False)
        item = self.listOfIncomeSEK.item(0)
        item.setText(_translate("MainWindow", "Amount:"))
        item = self.listOfIncomeSEK.item(1)
        item.setText(_translate("MainWindow", "0"))
        self.listOfIncomeSEK.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listOfExpensesSEK.isSortingEnabled()
        self.listOfExpensesSEK.setSortingEnabled(False)
        item = self.listOfExpensesSEK.item(0)
        item.setText(_translate("MainWindow", "Amount:"))
        item = self.listOfExpensesSEK.item(1)
        item.setText(_translate("MainWindow", "totalFixed"))
        item = self.listOfExpensesSEK.item(2)
        item.setText(_translate("MainWindow", "Subscriptions"))
        item = self.listOfExpensesSEK.item(3)
        item.setText(_translate("MainWindow", "insurance"))
        item = self.listOfExpensesSEK.item(4)
        item.setText(_translate("MainWindow", "rent"))
        item = self.listOfExpensesSEK.item(5)
        item.setText(_translate("MainWindow", "other"))
        item = self.listOfExpensesSEK.item(10)
        item.setText(_translate("MainWindow", "totalvariable"))
        item = self.listOfExpensesSEK.item(11)
        item.setText(_translate("MainWindow", "transport"))
        item = self.listOfExpensesSEK.item(12)
        item.setText(_translate("MainWindow", "entertainment"))
        item = self.listOfExpensesSEK.item(13)
        item.setText(_translate("MainWindow", "clothes"))
        item = self.listOfExpensesSEK.item(14)
        item.setText(_translate("MainWindow", "hygien"))
        item = self.listOfExpensesSEK.item(15)
        item.setText(_translate("MainWindow", "food"))
        item = self.listOfExpensesSEK.item(16)
        item.setText(_translate("MainWindow", "bills"))
        item = self.listOfExpensesSEK.item(17)
        item.setText(_translate("MainWindow", "others"))
        self.listOfExpensesSEK.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "Back"))
        self.label_3.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "Savings"))
        __sortingEnabled = self.savingsList.isSortingEnabled()
        self.savingsList.setSortingEnabled(False)
        item = self.savingsList.item(0)
        item.setText(_translate("MainWindow", "Type:"))
        item = self.savingsList.item(1)
        item.setText(_translate("MainWindow", "Saving goal"))
        item = self.savingsList.item(2)
        item.setText(_translate("MainWindow", "Buffert"))
        self.savingsList.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.savingsListSEK.isSortingEnabled()
        self.savingsListSEK.setSortingEnabled(False)
        item = self.savingsListSEK.item(0)
        item.setText(_translate("MainWindow", "Amount:"))
        item = self.savingsListSEK.item(1)
        item.setText(_translate("MainWindow", "0"))
        item = self.savingsListSEK.item(2)
        item.setText(_translate("MainWindow", "0"))
        self.savingsListSEK.setSortingEnabled(__sortingEnabled)
        self.label_5.setText(_translate("MainWindow", "Current budget:"))
